In [1]:
import pandas as pd
import os

SYNTHETIC_PATH = r"data\synthetic"
PROCESSED_PATH = r"data\processed"

# Load all three datasets
train_real     = pd.read_csv(os.path.join(PROCESSED_PATH,  'train_real.csv'))
synthetic_ctgan   = pd.read_csv(os.path.join(SYNTHETIC_PATH, 'synthetic_ctgan.csv'))
synthetic_tabddpm = pd.read_csv(os.path.join(SYNTHETIC_PATH, 'synthetic_tabddpm.csv'))

print("REAL TRAIN:")
print(f"  Shape:          {train_real.shape}")
print(f"  Mortality rate: {train_real['HOSPITAL_EXPIRE_FLAG'].mean()*100:.1f}%")

print("\nCTGAN SYNTHETIC:")
print(f"  Shape:          {synthetic_ctgan.shape}")
print(f"  Mortality rate: {synthetic_ctgan['HOSPITAL_EXPIRE_FLAG'].mean()*100:.1f}%")

print("\nTabDDPM SYNTHETIC:")
print(f"  Shape:          {synthetic_tabddpm.shape}")
print(f"  Mortality rate: {synthetic_tabddpm['HOSPITAL_EXPIRE_FLAG'].mean()*100:.1f}%")

print("\nShapes match:", 
      train_real.shape == synthetic_ctgan.shape == synthetic_tabddpm.shape)

REAL TRAIN:
  Shape:          (25508, 34)
  Mortality rate: 10.6%

CTGAN SYNTHETIC:
  Shape:          (25508, 34)
  Mortality rate: 23.1%

TabDDPM SYNTHETIC:
  Shape:          (25508, 34)
  Mortality rate: 8.9%

Shapes match: True

In [2]:
df_1 = pd.read_csv('data/synthetic/synthetic_ctgan.csv')
df_2 = pd.read_csv('data/synthetic/synthetic_tabddpm.csv')

In [3]:
df_1.head()

,AGE,GENDER,LOS,lab_base_excess,lab_bicarbonate,lab_bun,lab_creatinine,lab_glucose,lab_haemoglobin,lab_lactate,...,lab_potassium_missing,lab_sodium_missing,lab_wbc_missing,admtype_EMERGENCY,admtype_URGENT,insurance_Medicaid,insurance_Medicare,insurance_Private,insurance_Self Pay,HOSPITAL_EXPIRE_FLAG
0,1.370504,0,1.197137,2.147571,-0.340830,0.343552,-1.189582,1.207850,-0.216778,1.259106,...,0,0,0,1,0,0,1,0,0,0
1,-0.271847,1,-0.576285,0.005702,-0.035792,0.020974,-0.068974,-0.044213,0.044744,0.007406,...,1,1,1,1,0,0,0,1,0,0
2,0.998736,1,-0.004873,1.373339,-0.026004,-0.047284,-0.408852,0.334939,-0.686178,-1.063205,...,0,0,0,0,0,0,1,1,0,0
3,0.637432,1,-0.592616,0.011694,-1.413189,2.675920,1.252138,-1.286815,-0.409183,0.000147,...,0,0,0,1,0,1,1,0,0,1
4,0.830942,1,-0.982038,0.000283,-2.076495,1.857812,0.981852,-0.146932,-1.244215,1.510386,...,0,0,0,1,0,0,1,0,0,0

In [4]:
df_1.describe()

,AGE,GENDER,LOS,lab_base_excess,lab_bicarbonate,lab_bun,lab_creatinine,lab_glucose,lab_haemoglobin,lab_lactate,...,lab_potassium_missing,lab_sodium_missing,lab_wbc_missing,admtype_EMERGENCY,admtype_URGENT,insurance_Medicaid,insurance_Medicare,insurance_Private,insurance_Self Pay,HOSPITAL_EXPIRE_FLAG
count,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,...,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000
mean,0.074695,0.650345,-0.129326,-0.006093,-0.013336,0.158624,-0.070187,-0.118667,-0.032185,0.019137,...,0.182649,0.198369,0.196723,0.841736,0.051631,0.078524,0.501999,0.356241,0.035165,0.230790
std,0.968539,0.476870,0.847352,1.318824,0.900134,0.968872,0.881145,0.846140,0.868914,0.826589,...,0.386386,0.398779,0.397529,0.364996,0.221285,0.269000,0.500006,0.478897,0.184201,0.421347
min,-3.257290,0.000000,-3.487148,-5.199338,-2.958556,-2.747688,-2.683535,-2.668568,-3.000604,-2.525946,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-0.568370,0.000000,-0.667396,0.002834,-0.619918,-0.474229,-0.765971,-0.749052,-0.707517,-0.001387,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,-0.033102,1.000000,-0.118858,0.006599,-0.026964,0.066582,-0.072491,-0.120102,0.010201,0.002726,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,0.855146,1.000000,0.405802,0.011135,0.567236,0.749427,0.505105,0.396911,0.529256,0.006999,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
max,2.998751,1.000000,3.484294,2.859358,3.156727,3.438021,2.790594,2.811463,2.973815,2.766996,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
df_2.head()

,AGE,GENDER,LOS,lab_base_excess,lab_bicarbonate,lab_bun,lab_creatinine,lab_glucose,lab_haemoglobin,lab_lactate,...,lab_potassium_missing,lab_sodium_missing,lab_wbc_missing,admtype_EMERGENCY,admtype_URGENT,insurance_Medicaid,insurance_Medicare,insurance_Private,insurance_Self Pay,HOSPITAL_EXPIRE_FLAG
0,-1.285245,0,-1.093390,0.004324,-1.303147,-1.973700,-1.419481,-1.156190,-1.649493,0.289024,...,0,0,0,0,0,0,0,1,0,0
1,1.355957,1,-0.348322,-1.784017,-0.379648,0.948058,1.194568,0.559689,0.228969,0.340605,...,0,0,0,1,0,0,1,0,0,0
2,-0.623124,1,0.664057,-0.002341,-0.529094,-1.287780,-0.910146,-0.303586,1.683091,-0.004564,...,0,0,0,1,0,1,0,0,0,0
3,0.370436,1,-1.419881,-0.050120,1.083666,-0.274137,-0.143106,-0.446821,-0.102504,-0.014830,...,0,0,0,0,0,0,1,0,0,0
4,-0.012885,1,-0.132048,0.024546,-0.699683,0.458262,0.403084,0.213057,0.898421,-0.021328,...,0,0,0,1,0,0,0,0,0,0

In [6]:
df_2.describe()

,AGE,GENDER,LOS,lab_base_excess,lab_bicarbonate,lab_bun,lab_creatinine,lab_glucose,lab_haemoglobin,lab_lactate,...,lab_potassium_missing,lab_sodium_missing,lab_wbc_missing,admtype_EMERGENCY,admtype_URGENT,insurance_Medicaid,insurance_Medicare,insurance_Private,insurance_Self Pay,HOSPITAL_EXPIRE_FLAG
count,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,...,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000,25508.000000
mean,-0.005187,0.579779,-0.010259,-0.169673,-0.004719,-0.018605,-0.005249,-0.014795,0.005423,-0.020691,...,0.039752,0.041987,0.044182,0.825741,0.018896,0.069312,0.531402,0.371138,0.005136,0.089266
std,0.998914,0.493604,1.018303,1.693299,0.966135,0.978747,0.971789,0.992921,1.001578,0.885340,...,0.195380,0.200563,0.205504,0.379340,0.136161,0.253988,0.499023,0.483119,0.071481,0.285133
min,-3.840607,0.000000,-4.233759,-93.124620,-4.105712,-4.006934,-4.390138,-4.899708,-4.282659,-4.476716,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,-0.694658,0.000000,-0.721274,-0.019032,-0.624671,-0.663248,-0.626180,-0.655151,-0.656067,-0.045254,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,-0.011029,1.000000,-0.006176,0.004428,-0.005412,-0.022182,-0.016134,-0.008336,0.011254,-0.001825,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
75%,0.686165,1.000000,0.696727,0.027612,0.617612,0.621887,0.623071,0.625739,0.670350,0.036398,...,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
max,4.186559,1.000000,4.153282,4.581171,4.085116,4.060031,4.204868,3.904292,3.734378,5.400985,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000